name: telstream
description: "Stream Telegram videos seamlessly using a high-performance built-in media player powered by TDLib and MediaKit."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tdlib: ^1.6.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  flutter_riverpod: ^3.3.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#020617"
  android: true
  ios: true
  android_12:
    color: "#020617"
